name: Complete CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify dependencies
        working-directory: Battleship-main
        run: mvn dependency:resolve

      - name: Compile project
        working-directory: Battleship-main
        run: mvn clean compile

      - name: Run unit tests
        working-directory: Battleship-main
        run: mvn test

      - name: SonarQube Cloud analysis
        working-directory: Battleship-main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATIO